### ISSUE TITLE
Client error '403 Forbidden' for url

### ISSUE THREAD

**Issue by Enziak** [raylu/poecalc#10]
Hi
Yesterday i was using this site and everything was fine, today i get some errors on every character/account i checked.

`Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pigwig/pigwig.py", line 117, in __call__
    response = handler(request, **kwargs)
  File "/usr/src/app/./poecalc.py", line 36, in analyze_auras
    char_stats, char, skills = stats.fetch_stats(account, character)
  File "/usr/src/app/stats.py", line 48, in fetch_stats
    r.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 736, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'https://www.pathofexile.com/character-window/get-items'
For more information check: https://httpstatuses.com/403
`

**Comment by Enziak** [comment]
I forgot to add, every profile was public and you could view it or import it to pob.

**Comment by raylu** [comment]
thanks for letting me know! fixed 0abd79c946f66b908039784a60704b0c17aecec0
