### ISSUE TITLE
Error when trying to Calc Effect of Aurabot

### ISSUE THREAD

**Issue by Mirokira** [raylu/poecalc#21]
Basicly when i go to this: https://poecalc.fly.dev/auras/Hazaky/HazAuraAgain?aura_effect=
i get a python error.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pigwig/pigwig.py", line 117, in __call__
    response = handler(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/./poecalc.py", line 34, in analyze_auras
    char_stats, char, skills = stats.fetch_stats(account, character)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/stats.py", line 69, in fetch_stats
    tree, skills, stats = jewels.process_transforming_jewels(tree, skills, stats, character)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/jewels.py", line 133, in process_transforming_jewels
    tree = process_timeless_jewel(jewel, tree, get_radius(jewel, skills))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/jewels.py", line 167, in process_timeless_jewel
    jewel.transform(node)
  File "/usr/src/app/jewels.py", line 215, in transform
    self._transform_notable(node)
  File "/usr/src/app/jewels.py", line 222, in _transform_notable
    alt_mods = self.mapping[node["skill"]]
               ~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 44207
```

**Comment by raylu** [comment]
this character has an elegant hubris that turns testudo into axiom warden (which isn't allocated)

@Liberatorist, AFAICT this is just https://github.com/Liberatorist/TimelessEmulator missing the testudo node (44207) in `elegant_hubris_passives.txt`. but it looks like you already updated the data for 3.20 when you generated the files 2 days ago. any idea what's up with this?

**Comment by Liberatorist** [comment]
Yeah that was my bad. 
The node had the name "shield_mastery" in the for some reason, so it was filtered out.
I fixed this in the timeless jewel data
