### ISSUE TITLE
Something went wrong on importing my char

### ISSUE THREAD

**Issue by GregBe** [raylu/poecalc#26]
Account: GregBe
Char: GregBeVerfluchteZeichen
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pigwig/pigwig.py", line 117, in __call__
    response = handler(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/./poecalc.py", line 35, in analyze_auras
    char_stats, char, skills = stats.fetch_stats(account, character)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/stats.py", line 83, in fetch_stats
    return stats_for_character(character, skills)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/stats.py", line 105, in stats_for_character
    for _, node_stats in iter_passives(tree, masteries, skills):
  File "/usr/src/app/stats.py", line 122, in iter_passives
    node = tree['nodes'][str(h)]
           ~~~~~~~~~~~~~^^^^^^^^
KeyError: '14674'
```

**Comment by raylu** [comment]
I'm... pretty confused how you have that node. 14674 is https://github.com/grindinggear/skilltree-export/blob/3.19.0/data.json
```json
"name": "Faster Doom Gain",
"stats": [
    "Hexes have 50% increased Doom gain rate"
]
```
I searched the PoB repo to confirm and that node hasn't existed since 3.20: 
![image](https://user-images.githubusercontent.com/90059/230536744-63de63f7-5225-40ae-96c9-07bc1d2cb841.png)
